name: Node.js CI

on:
  push:
    branches: [dev, prod]

jobs:
  setup-runner:
    runs-on: [self-hosted, dev]
    outputs:
      myrunner: ${{ steps.set-myrunner.outputs.myrunner }}
    steps:
      - id: set-myrunner
        run: echo "::set-output name=myrunner::${GITHUB_REF#refs/heads/}"

  build:
    needs: setup-runner
    runs-on: ${{needs.setup-runner.outputs.myrunner}}
    environment: ${{needs.setup-runner.outputs.myrunner}}
    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        
    - name: Code Setup
      env:
        ENV_FILE: ${{ secrets.HELLO }}
      run: |
        npm ci
        sudo cp -r ${GITHUB_WORKSPACE} /home/ubuntu/
        sudo echo "${ENV_FILE}" >> ~/node-app/.env