# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, prod]

jobs:
  build:
    runs-on: [ "${secrets.BRANCH}" ]
    environment: dev
    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        
        
    - name: Setup env files
      env:
        ENV_FILE: ${{ secrets.HELLO }}
      run: |
        echo "${ENV_FILE}" > /home/ubuntu/.env
        echo ${{ steps.runner.outputs.runner }} > /home/ubuntu/etmp


    - name: Code Setup
      run: |
        npm ci
        sudo cp -r ${GITHUB_WORKSPACE} /home/ubuntu/
