# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Folder Setup
      run: |
        mkdir -p ~/my-app
        cp -r * ~/my-app
        
    - name: Setup env files
      env:
        QA_ENV_FILE: ${{ secrets.HELLO }}
        PROD_ENV_FILE: ${{ secrets.HELLO }}
      run: |
        cd ~/my-app
        echo "${QA_ENV_FILE}" > .env
        
        
    - name: Get branch name (merge)
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Get branch name (pull request)
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Debug
      run: echo ${{ env.BRANCH_NAME }}

    - name: Code Setup
      run: |
        cd ~/my-app
        npm ci
        npm test
        pm2 restart nodeApp
